### ISSUE TITLE
Habilitar suporte para configurar dinamicamente arquivo samconfig.toml

### ISSUE THREAD

**Issue by gilcesarf** [trustep/io.trustep.github.workflows#5]
Em algumas situações é necessário configurar dinamicamente (em tempo de execução do pipeline) os valores de certos parametros. Por exemplo, nos trechos  de template abaixo:

```yaml
Parameters:
  BasePathName:
    Type: String
    Description: BasePath onde o deploy da API ocorrera

  BasePathDiscriminator:
    Type: String
    Description: String para discriminar o basepath. Se concatenara o BasePath con 0 BasePathDiscriminator.
    Default: ""
```

```yaml
Resources:
  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Join 
                  - ""
                  - - !Ref BasePathName
                    - !Ref BasePathDiscriminator
      DomainName: !Ref CustomDomainName
      RestApiId: !Ref ManagerAuthSupport
      Stage: !Ref ManagerAuthSupport.Stage
```

Os parametros BasePathName e/ou BasePathDiscriminator poderiam ser configurados dinamicamente para mapear caminhos distintos conforme o branch que gatilhou o pipeline, adicionando por exemplo o nome da feature através do BashPathDiscriminator.

Para solucionar o problema é necessário adicionar parametros para realizar as substituições correspondentes em tempo de execução.
